Add user and subscription models
Vantar-Studios/event-media-api pull request #2
Opened 2023-11-12 03:49 UTC by eliotfgn

2023-11-12 12:58 UTC, YacineSteeve requested changes
Should be improved, IMO

2023-11-12 12:58 UTC, YacineSteeve commented on prisma/schema.prisma
> +  ANNUALLY
Typo: Annually => Yearly

2023-11-12 12:58 UTC, YacineSteeve commented on src/core/utils/prisma/prisma.module.ts
I dont think `Prisma` is a 'utility' in the project, so its directory should'nt be under `core/utils/` but just under `core/` instead.

2023-11-12 12:58 UTC, YacineSteeve commented on prisma/schema.prisma
> +  profilePic     Media?         @relation(fields: [mediaId], references: [id])
profilePic => `profilePicture`

2023-11-12 12:58 UTC, YacineSteeve commented on prisma/schema.prisma
> +  nextBillingDate  DateTime
The difference with`billingDate` ?

2023-11-12 12:58 UTC, YacineSteeve commented on prisma/schema.prisma
> +  PREMIUM_USER
Why PREMIUM_USER instead of PREMIUM ?

2023-11-12 13:01 UTC, eliotfgn commented on prisma/schema.prisma
> +  ANNUALLY
Oh you're right lmaoo

2023-11-12 13:02 UTC, eliotfgn commented on prisma/schema.prisma
> +  description String?
yup. The description field would be useful to improve seo on the web application since next Image require the alt.

2023-11-12 13:03 UTC, YacineSteeve commented on prisma/schema.prisma
> +  description String?
Beautiful

2023-11-12 13:03 UTC, eliotfgn commented on prisma/schema.prisma
> +  country        String
just for firstname, lastname, phoneNumber and country? adding a type won't change the schema in the db

2023-11-12 13:03 UTC, eliotfgn commented on prisma/schema.prisma
> +  profilePic     Media?         @relation(fields: [mediaId], references: [id])
shiet mabad

2023-11-12 13:05 UTC, eliotfgn commented on prisma/schema.prisma
> +  nextBillingDate  DateTime
billingDate is the actual date the user payed for the subscription, and next is the date he will subcribe again. I've added it in order to maybe add jobs for this date and send reminders...

2023-11-12 13:05 UTC, eliotfgn commented on prisma/schema.prisma
> +enum Plan {
no need to have plan features in the db

2023-11-12 13:06 UTC, YacineSteeve commented on prisma/schema.prisma
> +  country        String
The addresses have to be more complete than that. As there is a billinig feature:

- phoneNumber
- street
- postal code
- country
- ...

2023-11-12 13:07 UTC, eliotfgn commented on prisma/schema.prisma
> +  PREMIUM_USER
because there is a premium plan for regular user and a premium plan for organizer. But those names are not definitive

2023-11-12 13:08 UTC, YacineSteeve commented on prisma/schema.prisma
> +  nextBillingDate  DateTime
That's not the meaning of billingDate.
What you are saying is much more subscriptionDate.
Billing date is the date when the user will be charged each period (month or year) depending on it's plan.

2023-11-12 13:08 UTC, YacineSteeve commented on prisma/schema.prisma
> +enum Plan {
Thought that too. But are you OK with the two other fields ?

2023-11-12 13:09 UTC, eliotfgn commented on src/core/utils/prisma/prisma.module.ts
yeaah I was also wondering myself about where to put it right

2023-11-12 13:13 UTC, YacineSteeve commented on prisma/schema.prisma
> +  PREMIUM_USER
Okay, anyway I don't think these model really matches the pricing idea showed in the Figma.
It's more like there is two plan type, each one have one or more packages.

PlanType: Free, Organizer

Free plan packages: Free

Organizer plan packages: Bronze, Silver, Gold

2023-11-12 13:34 UTC, eliotfgn commented on prisma/schema.prisma
> +enum Plan {
Yes but no need to have a separate table in the database for them since we can just concate it to the subscription, it will be too much relations and then too much requests that we can just skip

2023-11-12 13:36 UTC, eliotfgn commented on prisma/schema.prisma
> +  PREMIUM_USER
No need to last on this details because actually the flow isnt totally clear at our level. But even if there is plan types then package we can just group them

2023-11-12 13:38 UTC, eliotfgn commented on prisma/schema.prisma
> +  PREMIUM_USER
Actually I get what you mean. I will add PlanType and PlanPackage

2023-11-12 13:39 UTC, eliotfgn commented on prisma/schema.prisma
> +  country        String
Do you recommend to have a table or just a type, because the type would be just for the dx, but the table for the db

2023-11-12 14:08 UTC, YacineSteeve commented on prisma/schema.prisma
> +  country        String
Just a type

2023-11-12 14:09 UTC, YacineSteeve commented on prisma/schema.prisma
> +  PREMIUM_USER
Great

2023-11-12 16:00 UTC, eliotfgn commented on prisma/schema.prisma
> +  country        String
then it doesn't bring something really new and will complicate the payload

2023-11-13 00:38 UTC, YacineSteeve approved these changes

2023-11-13 00:41 UTC, merged