Add Login endpoint
Vantar-Studios/event-media-api pull request #6
Opened 2023-11-20 13:51 UTC by eliotfgn

style: Apply prettier format to app module files

feat: Register auth guard

feat: Add login request dto

feat: Find user entity by email

feat: add login service

feat: Add auth controller

fix: TokenService import in auth service

fix: Add SkipAuth decorator to auth controllers

feat: Add timeout interceptor

fix: Pass response through Nest pipeline

feat: Use cookies instead of authorization to get access token

fix: Only send user profile as response

2023-11-20 14:06 UTC, YacineSteeve requested changes
Let's discuss about the changes.

2023-11-20 14:06 UTC, YacineSteeve commented on src/core/features/auth/auth.controller.ts
> +        const loginResponse: AuthResponseDto = await this.authService.login(payload);
A `Dto` as return type ?

It is better the endpoints return `AuthResponse['user']` instead of `UserResponse`

2023-11-20 14:06 UTC, YacineSteeve commented on src/core/features/auth/dto/auth-response.dto.ts
> +    token: string;
`LoginResponseDto` instead, right ?

And you can then infer the `LoginResponse` type.

2023-11-20 14:06 UTC, YacineSteeve commented on src/core/features/user/user.service.ts
> +        return this.prismaService.user.findUniqueOrThrow({
I think `findUnique` is better here.

So that we can do checks like `if (!foundUser) { ...}` instead of setting up a whole try-catch block.

2023-11-21 00:25 UTC, eliotfgn commented on src/core/features/auth/dto/auth-response.dto.ts
> +    token: string;
Auth response since the same response type can be sent from register

2023-11-21 00:26 UTC, eliotfgn commented on src/core/features/user/user.service.ts
> +        return this.prismaService.user.findUniqueOrThrow({
With the orThrow the exception is thrown for us and the method execution stops

2023-11-21 01:43 UTC, YacineSteeve commented
Okay

2023-11-21 01:45 UTC, YacineSteeve approved these changes

2023-11-21 01:45 UTC, merged